version: "3"
services:
  client:
    build: ./client
    ports:
      - "3001:3001"
    volumes: 
      - ./client:/client
    depends_on:
      - server
  server: 
    build: ./
    ports:
      - "3000:3000"
